const quotes = [
	"Fucker McChucker! Motherfucker!",
	"For every Chuck, there's a Sneed!",
	"Home of the Tendies! Now with 99.5% soy!",
	"Motos are love! Motos are life!",
	"For a bygone era, you had to be there.",
	"You will never be the main character.", 
	"ROBLOX: Powering Greed!",
	"Bing Bing Wahoo!",
	"I found the HACKERMAN! He's...",
	"He can't keep getting away with it!",
	"Gotta be quick!",
	"Mario is real. RUN!",
	"Billions must browse the site!",
	"Totally not funded by the Happy Kecleon Merchants.",
	"Half Life 3 will come out on... fuck idk",
	"Read this quote for FREE VIP!",
	"POKEMON! Corrupting the youth since 1998.",
	"Warning! Content may not provide comfort.",
	"You will browse my site, and you will be happy!",
	"Don't look behind you.",
	"I saw the Herobrine! 100% REAL!",
	"ALL TEH MEMEZ R MINEZ!",
	"Where's Moot?",
	"It's a subtle joke.",
	"There's Dice Bytes in my computer!",
	"I bought clothes from the soup store.",
	"How's your 'Pokemon Killer' doing?",
	"Your only hope for a future.",
	"My ROFLcopter goes SOI SOI SOI!",
	"Nothing ever happens!",
	"Something happened?!",
	"It's more than 2, and less than 4.",
	"It just works!",
	"Who's laughing now!",
	"I got a bad feeling about this.",
	"They glow in the dark.",
	"Blockland! The building game that's in a 'Badspot'?",
	"The fastest computer in the world is the most expensive.",
	"All your bases are belong to us!",
	"Somebody set us up the, the Bobomb!",
	"Plastic Men and Iron Blades.",
	"I R TEH PWNZ0R!",
	"Powered by Shrooms!"
];

document.getElementById('randomQuote').textContent = quotes[Math.floor(Math.random() * quotes.length)];